project:
  type: website

website:
  title: "ISSS608 VAA G7"
  navbar:
    left:
      - href: proposal.qmd
        text: Proposal
         
      - href: https://isss608-vaa-sm.shinyapps.io/shiny1/
        text: R shinyApp
            
      - href: poster.pdf
        text: Poster
        
      - href: userguide.pdf
        text: User Guide

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

